### ISSUE TITLE
Putting the images inside a background frame ( bigger than actual image size )

### ISSUE THREAD

**Issue by shrutig3** [iosscripts/iosslider#147]
Hi,

I have an image as a background frame which is bigger in size than the actual images to slide. Its like an ipad / iphone frame inside which I have to slide the images.

I am trying to achieve this by setting width and height but its not working.

Any help is appreciated.

Thanks!

**Comment by iosscripts** [comment]
Do you have a demo I can look at?

**Comment by shrutig3** [comment]
I don't have a demo,

But here is my code if it helps,

Styles 

``` css
#container {
            width:1468px;
            height:1236px;
            background:url(xyz.png) no-repeat;
        }

            .iosSlider {
            width: 1024px;
            height: 768px;
        }
```

HTML

``` html
<div id="container">
<div class = 'iosSlider'>
        <div class = 'slider'>
            <div class = 'item' id = 'item1'></div>
            <div class = 'item' id = 'item2'></div>
            <div class = 'item' id = 'item3'></div>
            <div class = 'item' id = 'item4'></div>
            <div class = 'item' id = 'item5'></div>
            <div class = 'item' id = 'item6'></div>
        </div>  
</div>
</div>
```

So, my container frame is of size 1468 \* 1236 and my individual images which I need the slide for are of size 1024*768

The main container background image has a blank part in between where these images should fit in ( exactly like an ipad frame should be consistent and images should just slide inside. ) hope this helps!

Thanks!

**Comment by iosscripts** [comment]
Where's the slider and item CSS? I still don't get what you are trying to do :S. 

If you don't have a demo because of hosting issues, just email a zip of your issue to contact@iosscripts.com and I'll take a look at that.

**Comment by shrutig3** [comment]
Here is the complete code,

```
        #container {
            width:1468px;
            height:1236px;
            background:url(xyz.png) no-repeat 0px 0px;
        }

        .iosSlider {
            width: 1024px;
            height: 768px;
        }

        .iosSlider .slider {
            width:100%;
            height:100%;                
        }

        .iosSlider .slider .item {
            position: relative;
            top:0px;
            left:0px;

            width: 1024px;
            height: 768px;
            margin: 0 0 0 0;
        }

        .iosSlider .slider #item1 {
            background: url(abc.jpg) no-repeat 0 0;
        }

        .iosSlider .slider #item2 {
            background: url(abc.jpg) no-repeat 0 0;
        }

        .iosSlider .slider #item3 {
            background: url(abc.jpg) no-repeat 0 0;
        }

        .iosSlider .slider #item4 {
            background: url(abc.jpg) no-repeat 0 0;
        }

        .iosSlider .slider #item5 {
            background: url(abc.jpg) no-repeat 0 0;
        }

        .iosSlider .slider #item6 {
            background: url(abc.jpg) no-repeat 0 0;
        }
```

HTML

```
                <div id="container">
                  <div class = 'iosSlider'>
                    <div class = 'slider'>
                          <div class = 'item' id = 'item1'></div>
                          <div class = 'item' id = 'item2'></div>
                      <div class = 'item' id = 'item3'></div>
                      <div class = 'item' id = 'item4'></div>
                      <div class = 'item' id = 'item5'></div>
                     <div class = 'item' id = 'item6'></div>
                   </div>   
                  </div>
                </div>
```

Look at the image here for ipadFrame.

http://ryokkai.deviantart.com/art/ipad-frame-176492578

Like in this image there is white part, where I have to show the item images sliding. so the size of those images exactly fit in this white part. I am setting this ipad frame image as background to my "container" div and now want the images sliding at a particular position where the white part is present.

I hope this is more clear, if not let me know.

Thanks!

**Comment by iosscripts** [comment]
So here it is.

The iosSlider JS code: 

``` js
$('.iosSlider').iosSlider({
    desktopClickDrag: true,
    snapToChildren: true,
    stageCSS: {
        position: 'absolute'
    }
});
```

Add in the stageCSS part to your code. That's critical.

And then the CSS:

``` css
#container {
    position: relative;
    width: 1468px;
    height: 1236px; 
    background: <some bg image>;
}

.iosSlider {
    width: 1024px;
    height: 768px;

    /* update these margins to fit your frame*/
    margin-top: <some top offset>px;
    margin-left: <some left offset>px;
}
```

Let me know if that works.
