### ISSUE TITLE
Flexible height slider

### ISSUE THREAD

**Issue by bawpcwpn** [iosscripts/iosslider#154]
Hi guys,

Trying to make a flexible height and width slider i.e. the actual content of my slides varies in height. 

Is it possible to do this using a callback on onSlideChange that would find the current height of the slide and use jQuery to set the css of the slider to be that new height?

Thanks for any assistance!

**Comment by iosscripts** [comment]
There is a solution but slides will need to have a set px height.

``` js
$(document).ready(function() {

    $('.iosSlider').iosSlider({
        /* other parameters */

        /* add these */
        responsiveSlideContainer: false,
        stageCSS: {
            'overflow': 'visible'
        }
    });

});
```

and my css. 

``` css
.iosSlider {
    width: 100%;
    height: 100%;
}

.iosSlider .slider {
    width: 100%;
    height: 100%;
}

.iosSlider .slider .item {
    width: 100%;
    height: 100%;
}

.iosSlider .slider .item1 {
    height: 600px;
}

.iosSlider .slider .item2 {
    height: 800px;
}

.iosSlider .slider .item3 {
    height: 400px;
}
```

Let me know if that works.
