### ISSUE TITLE
'padding: 0' on lists makes the image left to the active slide don't appear on load.

### ISSUE THREAD

**Issue by betoalanis** [iosscripts/iosslider#196]
I'm using this markup for my slider (for semantics):

```
<div class='iosSliderContainer'>
  <div class="iosSlider">
    <ul class="slider">
      <li>
        <figure>
          <img>
           ...
```

I'm currently using the latest version of iosSlider (1.1.59) and jquery 1.9.0  - I had tried with older versions of BOTH scripts to check any difference and the bug is still there. I tested in FF and Chrome, so it's not a Browser bug.

What happens is that the image left to the active slide doesn't appear on load, until you interact with the slider; same thing that happened in Issue #152 the apparently was in general, this bug only happens AFAIK with ul and ol while resetting the padding.

Also; I don't know if this goes along this same issue, but if you swipe through the images fast in any direction you can see some of them taking too long too show, making the background show.

**Comment by marcwhitbread** [comment]
There are 2 issues here.
- Lack of CSS. on the iosSlider, slider, and slide elements. In your example you have applied none. See the tutorial for default CSS.
- Approach to centering the slide via snapSlideCenter is incorrect. You simply need to set a width on the iosSlider element to be greater than the width of the slide element. Then the slide element will center within the iosSlider element. Also, In your example you are overriding the overflow property and getting unexpected results... which can happen.

Below is a minor modification of example 12 - Fluid height image slides. For my example, I have used the image width of 900px. Try it this way: 

HTML:

``` html
<div class = 'fluidHeight'>

    <div class = 'sliderContainer'>

        <div class = 'iosSlider'>

            <div class = 'slider'>

                <div class = 'item'>
                    <img src = 'h-slider-1.jpg' />
                </div>

                <div class = 'item'>
                    <img src = 'h-slider-2.jpg' />
                </div>

                <div class = 'item'>
                    <img src = 'h-slider-3.jpg' />
                </div>

                <div class = 'item'>
                    <img src = 'h-slider-4.jpg' />
                </div>

            </div>

        </div>

    </div>

</div>
```

CSS:

``` css
.fluidHeight {
    position: relative;
    width: 100%;
    height: 300px;
}

/* 
 * below 900px, switch to percentage based responsive height.
 * padding of 33.333% is calculated by using the 
 * image ratio 300px/900px = .333 * 100% = 33.333% 
 */
@media screen and (max-width: 900px) {

    .fluidHeight {
        height: 0;
        padding: 0 0 33.333% 0;
    }

}

.sliderContainer {
    position: absolute;
    width: 100%;
    height: 100%;
}

.iosSlider {
    width: 100%;
    height: 100%;
    background: #aaa;
}

.iosSlider .slider {
    width: 100%;
    height: 100%;
}

.iosSlider .slider .item {
    position: relative;
    top: 0;
    left: 0;

    max-width: 900px;
    width: 100%;
    height: 100%;
}

.iosSlider .slider .item img {
    position: relative;
    top: 0;
    left: 0;
    max-width: 900px;
    width: 100%;
    margin: 0 auto;
}
```

JS:

``` js
$('.iosSlider').iosSlider({
    snapToChildren: true,
    desktopClickDrag: true,
    infiniteSlider: true,
    snapSlideCenter: true
});
```

Let me know if you have any questions.
