### ISSUE TITLE
onSlideComplete isn't firing

### ISSUE THREAD

**Issue by ashack293** [iosscripts/iosslider#281]
I'm using version 1.2.27, code below:

``` javascript
featuredSliderArgs =  {
            snapToChildren :            true,
            desktopClickDrag :          false,
            keyboardControls :          true,
            responsiveSlideContainer :  false,
            autoSlide :                 true,
            startAtSlide :              1, 
            infiniteSlider :            true,
            navPrevSelector :           $('#featuredControls .gallery-prev'),
            navNextSelector :           $('#featuredControls .gallery-next'),
            snapSlideCenter :           true,
            onSlideComplete :   function(args){ 
                 console.log('this will never happen');
           }
}

        $('#featuredSlider').iosSlider(featuredSliderArgs);
```

See above, the callback onSlideComplete is never triggered. Edited to remove confusing description. Was trying to isolate another problem and got ahead of myself.

**Comment by marcwhitbread** [comment]
Your title is throwing me off. What does your message have to do with the title?

**Comment by ashack293** [comment]
Sorry about that, edited. The other issue I vaguely alluded to was fixed another way.

**Comment by marcwhitbread** [comment]
Hmmm. Maybe it has something to do with your HTML/CSS? I just popped your settings into example 1 and the console log fires successfully.

Anything unique about your implementation?

**Comment by ashack293** [comment]
The slider is stretched to the width of the page, with the current slide centered in the page and the prev / next slides partially visible.

``` css

#featuredSlider {
            &.iosSlider {
                position: relative;
                top: 0;
                left: 0px;
                right: 0px;
                margin: 0px auto;
                overflow-y: hidden;
                width:  100%;
                height: 500px;
                 .slider {
                    width: 950px;
                    height: 500px;
                    margin: 0px auto;

                    .slide {
                        float: left !important;
                        width: 950px;
                        height: 500px;
                        border: none;
                    }
                }
            }
        }    

```

``` html
<div id="featuredSlider" class="iosSlider">
     <div class="slider">
     <div class="slide slide-item">
        <img class="slider-img" />
    </div>
  </div>
</div>
```
