### ISSUE TITLE
Black twitch/flicker on slide click

### ISSUE THREAD

**Issue by JanMesaric** [iosscripts/iosslider#319]
I'm having a problem using an iPad 3 latest version of ios running an app using phonegap 2.7.

When clicking on slider I get a short twitch/flicker that is the same as the size of slider container. 

The issue is visible and harms user experience. 

Has anyone found a solution?

Sincerely, 
Jan

**Comment by marcwhitbread** [comment]
Is the color produced by `-webkit-tap-highlight-color` by any chance? It shouldn't be occurring on iOS but in PhoneGap I'm not sure.

Try setting:

``` css
body {
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}
```
