### ISSUE TITLE
iosSlider does not appear when using JQM multi-page template

### ISSUE THREAD

**Issue by Waynzel** [iosscripts/iosslider#72]
Hello everyone,

I am currently developing my first hybrid app using the jquery mobile framework and worklight. All my content is in one HTML file using the JQM multi-page template.

http://jquerymobile.com/demos/1.1.1/docs/pages/multipage-template.html

In one page (another page appears first) I would like to use iosSlider but the slider box does not show up directly. Only after a page refresh (which is impossible within a mobile application) the slider box appears.

I tried many things but have not find a workaround yet. The implementation should be fine as I am using more or less a clean slider box for testing purposes.

I really appreciate any hint.

Many thanks and regards,
Waynzel

HTML code (extractions):

``` html
<head>...
        <script language="Javascript" type="text/javascript" src="js/core/jquery.js"></script>
        <script language="Javascript" type="text/javascript" src="js/core/jquery.iosslider.min.js"></script>
        <script language="Javascript" type="text/javascript" src="js/core/jquery.mobile-1.1.1.min.js"></script>
        <script language="Javascript" type="text/javascript" src="js/core/jquery.tools.min.js"></script>
        <script language="Javascript" type="text/javascript" src="js/core/scroll.js"></script>
        <script language="Javascript" type="text/javascript" src="js/core/video.min.js"></script>
        <script language="Javascript" type="text/javascript" src="js/core/functions.js"></script>
...</head>

<body> ....

        <!-- Page - Erkenntnisse -->

        <div data-role="page" data-theme="c" id="erkenntnisse" data-dom-cache="true">
            <!-- Header -->
            <div data-role="header" data-theme="c" data-position="fixed" data-id="header">
                <h1>S3 Studie 2012</h1>
                <a href="#uebersicht" data-icon="grid" data-iconpos="notext" data-transition="slideup">Home</a>
            </div>
            <!-- Footer -->
            <div data-role="footer" data-id="foo1" data-position="fixed">
                <div data-role="navbar" class="s3_footer">
                    <ul>
                        <li><a href="#uebersicht" id="s3_overview" data-icon="custom" data-transition="slideup"></a></li>
                        <li><a href="#hintergrund" id="s3_study" data-icon="custom" data-transition="slidedown" class="ui-btn-active ui-state-persist"></a></li>
                        <li><a href="#kontakt" id="s3_contact" data-icon="custom" data-transition="slideup"></a></li>
                        <li><a href="#extras" id="s3_more" data-icon="custom" data-transition="slideup"></a></li>
                    </ul>
                </div>
            </div>
            <!-- Content -->
            <div data-role="content" data-theme="c" style="background:transparent;">
                <h2>Erkenntnisse</h2>
                Text


                <!-- Slider -->
                Test
                <div class="iosSlider">
                    <div class="slider">
                        <div class="slide" id="item1">Test 1</div>
                        <div class="slide" id="item2">Test 2</div>
                        <div class="slide" id="item3">Test 3</div>
                    </div>
                    <div class = "iosSliderButtons">
                        <div class="button"></div>
                        <div class="button"></div>
                        <div class="button"></div>
                    </div>
                </div>
                <!-- Slider End -->


                <!-- Content navigation -->
                <div data-role="controlgroup" data-type="horizontal" data-mini="true">
                    <a href="#hintergrund" data-theme="c" data-role="button" data-transition="reverse slide">Hintergrund</a>
                    <a href="#erkenntnisse" data-theme="b" data-role="button" data-transition="slide" class="ui-disabled">Erkenntnisse</a>
                    <a href="#schlussfolgerung" data-theme="c" data-role="button" data-transition="slide">Fazit</a>
                </div>
            </div>
        </div>

...</body>
```

JS:

``` js
$(document).ready(function() {

    /* some custom settings */
    $('.iosSlider').iosSlider({
        snapToChildren: true,
        scrollbar: false,
        desktopClickDrag: true,
        onSlideChange: changeSlideIdentifier
    });

    $('div').iosSlider('update');

});
```

CSS (extractions):

``` css
.iosSlider {
    /* required */
    position: relative;
    top: 0;
    left: 0;
    overflow: hidden;

    /* optional */
    width:450px;
    height:300px;
}

/* slider */
.iosSlider .slider {
    /* required */
    width: 100%;
    height: 100%;
}

/* slide */
.iosSlider .slider .slide {
    /* required */
    float: left;

    /* optional */
    width: 450px;
    height: 300px;
}

.iosSliderButtons {
    position: absolute;
    bottom: 10px;
    left: 10px;
    width: 200px;
    height: 10px;
}

.iosSliderButtons .button {
    float: left;
    width: 9px;
    height: 9px;
    background: #999;
    margin: 0 10px 0 0;
    opacity: 0.25;
    filter: alpha(opacity:25);
    border: 1px solid #000;
}

.iosSliderButtons .selected {
    background: #000;
    opacity: 1;
    filter: alpha(opacity:100);
}

/* slider end */
```
